### ISSUE TITLE
Hardcoded paths in tests

### ISSUE THREAD

**Issue by reidma** [drifted-in/planisphere-core#2]
When I try to create the package in Maven, it complains about missing files planisphere.svg and planisphere_printDefault_01.svg  Do these need to be included in the repository?

**Comment by jan-tosovsky-cz** [comment]
@reidma thanks for letting me know. Those files are referenced in tests. In my local copy they are present hence no error was reported so I overlooked that. You can ignore this error and use the 'build' goal instead. I'll update tests accordingly in near future.

**Comment by jan-tosovsky-cz** [comment]
Fixed via https://github.com/drifted-in/planisphere-core/commit/ba881c36acf07b5e6b5b1994ec03bdcfbc9d141b.
