### ISSUE TITLE
Longitude support

### ISSUE THREAD

**Issue by yasserlens** [drifted-in/planisphere-core#3]
Hello,

I took a quick look at the code and couldn't find a way to set the observer's longitude - am I missing something or was this not intended? Are you planning to add support for it?

Thank you!

**Comment by ecorm** [comment]
Only the latitude is needed for generating a planisphere. Every place on Earth along the same latitude will see the same view of the sky. The only difference is the time when it gets dark.

The only way longitude would matter is the difference between local midnight and "true" midnight. I don't think the difference is significant enough for a tool that helps you find constellations and bright stars.
